### ISSUE TITLE
Learning Strategy checkbox allows invalid selection

### ISSUE THREAD

**Issue by Jackabomb** [matthiasjordan/dahdidahdit#1]
Under the global settings, the Learning Mode setting contains two checkboxes, and it _is_ possible to deselect both. It seems these were likely meant to be radio buttons, in which exactly one is always selected.

When I deselect both, it seems to just keep using whatever was selected last. 
![Screenshot_20241028-000627](https://github.com/user-attachments/assets/282cb31e-e9a1-4288-92ae-dc7a9daeab01)

**Comment by matthiasjordan** [comment]
Thanks for your bug report. I can repro the issue and will fix it soon.

**Comment by matthiasjordan** [comment]
Please retest when you have the time and close the issue if it's fixed.

**Comment by Jackabomb** [comment]
It's working now!
