### ISSUE TITLE
APK name has changed from versionName to versionCode

### ISSUE THREAD

**Issue by licaon-kter** [matthiasjordan/dahdidahdit#3]
ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8293118953#L486

ref: https://github.com/matthiasjordan/dahdidahdit/releases/tag/release-1.12.0

was that intentional?

**Comment by matthiasjordan** [comment]
I was not aware that naming is critical. Apparently it is, so I fixed it.

**Comment by licaon-kter** [comment]
Thanks
